<a href="https://colab.research.google.com/github/RajeshVulasala/AI-ML/blob/main/Day_7_of_AI_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DAY-7
---
Strings and Dictionaries


**STRINGS:**

In [6]:
# EX:
Name = 'Rajesh Vulasala'
Clg = "Vel Tech University"
print(Name, Clg, sep='\n')

Rajesh Vulasala
Vel Tech University


In python STRINGS can be written in single and double quotes.

In [7]:
name = 'Rajesh Vulasala's Company
print(name)

SyntaxError: invalid syntax (2459305308.py, line 1)

We got an error so we can fix it by adding "**\**"

In [8]:
name = 'Rajesh Vulasala\'s Companay'
name

"Rajesh Vulasala's Companay"

below summarizes some important uses of the backslash character

```
I/P    O/P   
\'      '
\"      "
\\      \
\n      Next Line
```



In [10]:
# EX: Above Backlash examples
A  = 'What\'s up?'
B = "That's \"cool\""
C = "Look, a mountain:/\\"
D = "1\n2 3"
print(A, B, C, D, sep="\n")

What's up?
That's "cool"
Look, a mountain:/\
1
2 3


**Triple Quotes**: used to write multiple lines of strings in one variable ' """body"""

In [20]:
# EX:
Nam = """Rajesh
Vulasala"""
print(Nam)
# Nam == "Rajesh\nVulasala"

Rajesh
Vulasala


True

In [22]:
print("hello", end='')
print("Rajesh", end='')

hello
Rajesh

String Manipulation or retriving


```
1. index[0]
2. Slicing[0:3]
3. len()
```



In [23]:
# Ex: String Manipulation
print(len(Name), Name[2], Name[-3:], sep="\n")


15
j
ala


In [24]:
# Append is not posible in string
# EX:
Name[0] = 'V'

TypeError: 'str' object does not support item assignment

**STRING METHODS**
```
1. .upper()
2. .lower()
3. .index()
4. .startwith()
5. .endwith()
6. .split()
7. .join()
```



In [25]:
claim = "Pluto is a planet!"

In [26]:
# .upper()
claim.upper()

'PLUTO IS A PLANET!'

In [27]:
# .lower()
claim.lower()

'pluto is a planet!'

In [31]:
# .index
# searching for the first index of a sub string
claim.index('pla')

11

In [35]:
# .startwith()
claim.startswith('planet')
# claim.startswith(planet)

False

In [38]:
# .endswith()
claim.endswith('planet!')

True

In [39]:
# .split()
words = claim.split()
words

['Pluto', 'is', 'a', 'planet!']

In [42]:
# EX:
datestr = '27-06-2004'
day, month, year = datestr.split('-')
datestr

'27-06-2004'

In [43]:
# .join()
'/'.join([day, month, year])

'27/06/2004'

In [44]:
# Ex:
# we can put unicode characters right in our string literals :)
' 👏 '.join([word.upper() for word in words])

'PLUTO 👏 IS 👏 A 👏 PLANET!'

BUILDING STRINGS WITH " **.format()** "

In [45]:
# we can concatenate strings using + operator.
planet = 'Pluto'
planet + ', we miss you.'

'Pluto, we miss you.'

If we want to throw a non-string in between string we have to be careful to call str() on them

In [46]:
# without str()
position = 9
planet + ", you'll always be the " + position + "th planet to me."

TypeError: can only concatenate str (not "int") to str

In [47]:
# with str()
planet + ", you'll always be the " + str(position) + "th planet to me."

"Pluto, you'll always be the 9th planet to me."

Insted of typing all like planet and position we can use " **.formt(planet, position)**"

In [48]:
"{}, you'll always be the {}th planet to me.".format(planet, position)

"Pluto, you'll always be the 9th planet to me."

**DICTIONARIES**: Are python built-in data structures for mapping key values.

In [49]:
# Syntax
numbers = {'one':1, 'two':2, 'three':3}
numbers

{'one': 1, 'two': 2, 'three': 3}

Accessing &  Adding & replacing or changing the Values associated with an existing key.

In [50]:
# Accesseing
numbers['one']

1

In [51]:
# Adding
numbers['four'] = 4
numbers

{'one': 1, 'two': 2, 'three': 3, 'four': 4}

In [52]:
# Changing the key value
numbers['one'] = 'Mercury'
numbers

{'one': 'Mercury', 'two': 2, 'three': 3, 'four': 4}

**Dictionary Comprehensions**  
Same as lists

In [54]:
# EX:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
planet_first_latter = {planet: planet[0] for planet in planets}
planet_first_latter

{'Mercury': 'M',
 'Venus': 'V',
 'Earth': 'E',
 'Mars': 'M',
 'Jupiter': 'J',
 'Saturn': 'S',
 'Uranus': 'U',
 'Neptune': 'N'}

in Operator to check if the value is there or not.

In [55]:
'Earth' in planet_first_latter

True

In [56]:
'Rajesh' in planet_first_latter

False

In [60]:
# A for loop over a dictionary will loop over it keys
for i in numbers:
  print("{} = {}".format(i, numbers[i]))

one = Mercury
two = 2
three = 3
four = 4


we can access a collection of all the keys or all the values with  


```
1. dict.keys()
2. dict.values()
```



In [61]:
# Ex: .keys()
planet_first_latter.keys()

dict_keys(['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'])

In [62]:
# .values()
planet_first_latter.values()

dict_values(['M', 'V', 'E', 'M', 'J', 'S', 'U', 'N'])

we can get the values in sorted order.

In [63]:
','.join(sorted(planet_first_latter.values()))

'E,J,M,M,N,S,U,V'

3. dict.items()  
This method let us iterate over the keys and values of a dictioinary simultaneously

In [64]:
# EX: 1
for planet, i in planet_first_latter.items():
  print("{} begins with \"{}\"".format(planet.rjust(10),i))

   Mercury begins with "M"
     Venus begins with "V"
     Earth begins with "E"
      Mars begins with "M"
   Jupiter begins with "J"
    Saturn begins with "S"
    Uranus begins with "U"
   Neptune begins with "N"


In [65]:
help(dict)

Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |
 |  Built-in subclasses:
 |      StgDict
 |
 |  Methods defined here:
 |
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __gt__(self, value, /)
 |      Return self>va

Exercise:


In [69]:
# EX: 0a
a = ""
length = len(a)
length

0

In [70]:
# EX: 0b
b = "it's ok"
length = len(b)
length

7

In [71]:
# EX: 0c
c = 'it\'s ok'
length = len(c)
length

7

In [75]:
# EX: 0d
d = """hey"""
print(len(d))

3


In [76]:
# EX: 0e
e = '\n'
print(len(a))

0


1.
There is a saying that "Data scientists spend 80% of their time cleaning data, and 20% of their time complaining about cleaning data." Let's see if you can write a function to help clean US zip code data. Given a string, it should return whether or not that string represents a valid zip code. For our purposes, a valid zip code is any string consisting of exactly 5 digits.

HINT: str has a method that will be useful here. Use help(str) to review a list of string methods.

In [85]:
def is_valid_zip(zip_code):
  return len(zip_code) == 5 and zip_code.isdigit()
# print(is_valid_zip(516267))
is_valid_zip("516267")

False

Explanation:
* **why we given a string insted of a int**.  
* here zip_code could be a string an integer a list anything. python will accept any value but operator inside that must work with it.  
* why the error happens when we enter int because inside the function we used **len()** these will only work with string not with int.  
* we can pass the list or ditionary in place of zip_code but it will show error because of this part **zip_code.isdigit()** because the list and dictionary does not have **.isdigit()**


2.
A researcher has gathered thousands of news articles. But she wants to focus her attention on articles including a specific word. Complete the function below to help her filter her list of articles.

Your function should meet the following criteria:

* Do not include documents where the keyword string shows up only as a part of a larger word. For example, if she were looking for the keyword “closed”, you would not include the string “enclosed.”
* She does not want you to distinguish upper case from lower case letters. So the phrase “Closed the case.” would be included when the keyword is “closed”
* Do not let periods or commas affect what is matched. “It is closed.” would be included when the keyword is “closed”. But you can assume there are no other types of punctuation.

In [99]:
# Program
def word_research(doc_list, keyword):
  """
    Takes a list of documents (each document is a string) and a keyword.
    Returns list of the index values into the original list for all documents
    containing the keyword.

    Example:
    doc_list = ["The Learn Python Challenge Casino.", "They bought a car", "Casinoville"]
    >>> word_search(doc_list, 'casino')
    >>> [0]
    """
  indices = [] # list to hold the indices of matching documents
  for i, doc in enumerate(doc_list): # Iterate through the indices (i) and elements (doc) of documents
    tokens = doc.split() # Split the string doc into a list of words (according to whitespace)
    # Make a transformed list where we 'normalize' each word to facilitate matching.
    # Periods and commas are removed from the end of each word, and it's set to all lowercase.
    normalized = [token.rstrip('.,').lower() for token in tokens]
    # Is there a match? If so, update the list of matching indices.
    if keyword.lower() in normalized:
      indices.append(i)
  return indices

3.
Now the researcher wants to supply multiple keywords to search for. Complete the function below to help her.

(You're encouraged to use the word_search function you just wrote when implementing this function. Reusing code in this way makes your programs more robust and readable - and it saves typing!)

In [100]:
def multi_word_search(doc_list, keywords):
    """
    Takes list of documents (each document is a string) and a list of keywords.
    Returns a dictionary where each key is a keyword, and the value is a list of indices
    (from doc_list) of the documents containing that keyword

    >>> doc_list = ["The Learn Python Challenge Casino.", "They bought a car and a casino", "Casinoville"]
    >>> keywords = ['casino', 'they']
    >>> multi_word_search(doc_list, keywords)
    {'casino': [0, 1], 'they': [1]}
    """
    keyword_to_indices = {}
    for keyword in keywords:
        keyword_to_indices[keyword] = word_research(doc_list, keyword)
    return keyword_to_indices
doc_list = [
    "The Learn Python Challenge Casino.",
    "They bought a car and a casino",
    "Casinoville"
]

keywords = ['casino', 'they']

multi_word_search(doc_list, keywords)

{'casino': [0, 1], 'they': [1]}

Working with External Libraries.  
* imports in python.
* operator overloading.

**Imports**  
In python we can import external libraries

In [101]:
#  Start with importing with math
import math
print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [102]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [103]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [104]:
math.log(32, 2)

5.0

In [105]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.

    If the base is not specified, returns the natural logarithm (base e) of x.



In [106]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This i

In [107]:
import math as mt
mt.pi

3.141592653589793

In [108]:
import math
mt = math

In [109]:
from math import *
print(pi, log(32, 2))

3.141592653589793 5.0


import * makes all the module's variables directly accessible to you (without any dotted prefix).

Bad news: some purists might grumble at you for doing this.

Worse: they kind of have a point.

In [110]:
from math import *
from numpy import *
print(pi, log(32, 2))

TypeError: return arrays must be of ArrayType

What has happened? It worked before!

These kinds of "star imports" can occasionally lead to weird, difficult-to-debug situations.

The problem in this case is that the math and numpy modules both have functions called log, but they have different semantics. Because we import from numpy second, its log overwrites (or "shadows") the log variable we imported from math.

A good compromise is to import only the specific things we'll need from each module:

In [111]:
from math import log, pi
from numpy import asarray

Submodules  
We've seen that modules contain variables which can refer to functions or values. Something to be aware of is that they can also have variables referring to other modules.

In [112]:
import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:]
     )

numpy.random is a <class 'module'>
it contains names such as... ['set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [ ]:
# So if we import numpy as above, then calling a function in the random "submodule" will require two dots.


In [113]:
# Roll 10 dice
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

array([4, 5, 1, 1, 5, 2, 3, 4, 2, 1])

**Three tools for understanding strange objects:**  


1: type() (what is this thing?)

In [114]:
type(rolls)

numpy.ndarray

2: dir() (what can I do with it?)

In [115]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__'

In [116]:
# If I want the average roll, the "mean" method looks promising...
rolls.mean()

np.float64(2.8)

In [117]:
# Or maybe I just want to turn the array into a list, in which case I can use "tolist"
rolls.tolist()

[4, 5, 1, 1, 5, 2, 3, 4, 2, 1]

3: help() (tell me more)

In [118]:
# That "ravel" attribute sounds interesting. I'm a big classical music fan.
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])

    Return a flattened array.

    Refer to `numpy.ravel` for full documentation.

    See Also
    --------
    numpy.ravel : equivalent function

    ndarray.flat : a flat iterator on the array.



In [119]:
help(rolls)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any object that can

**Operator overloading**

In [120]:
# What's the value of the below expression?
[3, 4, 1, 2, 2, 1] + 10

TypeError: can only concatenate list (not "int") to list

In [121]:
# to fix that
rolls + 10

array([14, 15, 11, 11, 15, 12, 13, 14, 12, 11])

In [122]:
rolls <= 3

array([False, False,  True,  True, False,  True,  True, False,  True,
        True])

In [123]:
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [124]:
# Get the last element of the second row of our numpy array
x[1,-1]

np.int64(6)

In [125]:
# Get the last element of the second sublist of our nested list?
xlist[1,-1]

TypeError: list indices must be integers or slices, not tuple

Import tensorflow as tf  
Tensorflow: used for deeplearning.  
it makes extensive use of operator overloading

In [126]:
import tensorflow as tf
# Create two constants, each with value 1
a = tf.constant(1)
b = tf.constant(1)
# Add them together to get...
a + b

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [127]:
# how it works?
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
